### ISSUE TITLE
Add deadlines to conference info?

### ISSUE THREAD

**Issue by floledermann** [mocnik-science/giscience.net-data#1]
It would be super useful to provide a way to add deadlines for full/short papers to the conference data, and to be able to sort by upcoming deadline.

I would be willing to contribute some data, but first there needs to be a proposal on which field name(s) to use.

**Comment by mocnik-science** [comment]
Yes, I agree.  Good idea.  Thank you for this comment.  There is yet even some other interesting information missing, but the page will become more complete over time.  Let me have a look into how to add the deadlines.  I will keep you updated.  Contributions are highly welcome. ;)

**Comment by mocnik-science** [comment]
Deadlines have now been included for current conferences. For past conferences, they remain hidden. Have a look at COSIT 2019. There you will see the field names that I chose.

Are you fine with me adding you to the list of contributors?

**Comment by floledermann** [comment]
Great, I'll have a look and add more if needed (and promote the calendar) once I'm back at work.

Don't think my little suggestion justifies being listed  as contributor though, but do as you feel appropriate ;)

**Comment by mocnik-science** [comment]
Hi!  I think it would be great if we would add the deadlines for the current conferences.  Do you have time to add them, or should I?  If there arise any questions, please let me know.  Cheers, Franz-Benjamin

**Comment by floledermann** [comment]
I added the full paper deadline for AGILE 2019 in #4 - I am still desperately waiting for the call for ICC 2019 and other deadlines, so not more information available so far...

**Comment by mocnik-science** [comment]
Hi! I will merge later today. Thank you very much for your contribution! BTW: Where did you find the AGILE deadline? I did not find any website or call so far ;)

**Comment by floledermann** [comment]
I noted it down in the announcement session in Lund ;)

If you want to include only formally published calls, feel free to ignore the PR for now. But calls tend to get published awfully late lately, so I think it's better to have unofficial info and adjust later if needed.

I keep a calendar for myself where I put preliminary dates for when the deadlines *usually* are for conf. series, well in advance of the call being published - e.g. AGILE and ICC are usually in November, so I put Nov. 1st as a preliminary deadline. Maybe something like this could be included here as well, but maybe this is taking it too far... we would need to go down the whole "visualizing uncertainty" rabbit hole :smiley:

**Comment by mocnik-science** [comment]
I tend to not include uncertain dates – it should be the organizer who is first with announcing the deadlines. The announcement in Lund was, however, official, so the information should definitely be included. If you find some new deadlines, you are welcome to include them!
