### ISSUE TITLE
Current Conferences -> Sort by Date switches to All Conferences

### ISSUE THREAD

**Issue by floledermann** [mocnik-science/giscience.net-data#8]
I guess this doesn't belong to the data repository, but I couldn't find a public repo for the site...

When viewing "Current Conferences" (which should imo be the default because the historical info is not used so often I guess), selecting "Sort by date" resets to show all conferences, and also not sorted by date. (Browser: Current Chrome on Windows 10)

If sorting by date would work, and would be persisted in the URL, then I would really bookmark this and share among my colleagues - we have long been waiting for a conference calendar to replace our internal, Trello-based one.

Btw I would be willing to contribute directly to the code of the website if there would be an accessible repo to do that...

**Comment by mocnik-science** [comment]
An answer will arrive in about three weeks. I am on vacation and have only very bad access to the Internet.

**Comment by mocnik-science** [comment]
Oh yes, I see. I will fix this soon (until end of next week). I did, in fact, not (yet) share the code of the website. Will definitely think about doing so.

One reason for not yet persisting the sorting in the URL is that the plugin used to filter the data is not as stable as I hoped. I actually think about reimplementing the sorting on my own, which will result in more complex URLs that persist the sorting state.

**Comment by mocnik-science** [comment]
There was more work to do than expected.  The sorting issue should be resolved.  In particular, sorting does not automatically show all conferences, and the sorting options are now persisted in the URLs.  Are the issues you experienced resolved?

**Comment by floledermann** [comment]
Great work!
Personally, I would find it more intuitive if the date sorting order was reversed, i.e. the sooner conferences on top - but that's probably a subjective preference.

While we're at personal preferences, I find "sort by place" somewhat useless (assuming it sorts alphabetically by the name of the city), much more desirable would be to sort by upcoming deadlines. (But then the different types of deadlines would open another can of worms... For a start, I would simply use the earliest of the deadlines that has not passed yet)

One could also consider renaming "Current Conferences" to "Upcoming Conferences" to be more precise.

Sorry for the noise, but I believe has the potential to become an important resource for the GIScience community ;)

**Comment by mocnik-science** [comment]
Thanks for the nice words as well as for the suggestions/ideas.  I really appreciate them!

1) In general, the dates should sorted from sooner to later.  However, there was a minor but, which should be resolved now.  Can you confirm that I resolved the issue?

2) I actually like "sort by place" and would even like to add a map somewhen ;)  However, I understand the deadline issue, which is why I added "sorting by next deadline".  Like it!

3) Oh yes, "upcoming" is much better than "current". 

You do not have to apologize.  Quite to the contrary, I have to say thank you because your ideas are both valuable and welcome.

**Comment by floledermann** [comment]
OK so I will continue to contribute suggestions for improvements here ;)

The offer also stands that I would contribute directly to the code when possible, also if you would share it in private. I fully understand (from own experience) that opening code involves, besides the intellectual property question, issues of maintenance and support that you may not want to load upon yourself right now with this project.
